#!/usr/bin/env bash

declare -t SUGGESTED_FLATPAKS=(
    "com.github.marhkb.Pods"
    "com.github.tchx84.Flatseal"
    "com.jeffser.Alpaca"
    "com.mattjakeman.ExtensionManager"
    "com.obsproject.Studio"
    "com.rafaelmardojai.Blanket"
    "com.vivaldi.Vivaldi"
    "com.vscodium.codium"
    "fr.handbrake.ghb"
    "io.github.celluloid_player.Celluloid"
    "io.github.dvlv.boxbuddyrs"
    "io.github.vinser.burnfix"
    "io.mpv.Mpv"
    "net.nokyan.Resources"
    "org.audacityteam.Audacity"
    "org.bleachbit.BleachBit"
    "org.chromium.Chromium"
    "org.frescobaldi.Frescobaldi"
    "org.gimp.GIMP"
    "org.gnome.Boxes"
    "org.gnome.dspy"
    "org.gnome.TwentyFortyEight"
    "org.inkscape.Inkscape"
    "org.kde.kdenlive"
    "org.keepassxc.KeePassXC"
    "org.libreoffice.LibreOffice"
    "org.localsend.localsend_app"
    "org.mozilla.firefox"
    "org.mozilla.Thunderbird"
    "org.qbittorrent.qBittorrent"
)